### ISSUE TITLE
Change scaling of x axis to 2700 ? 

### ISSUE THREAD

**Issue by dffvb** [SiegeEngineers/aoe2-de-rating-charts#13]
Hi there, 

first of all: Thank you for providing this! Secondly: I think the value of the information could be increased of the scaling for 1v1 is changed to something to like 2700 ? Or 3000 ? Currently it is the same like team games with 4800 something...

**Comment by thbrown** [comment]
Hey Thanks! Yeah, when I first made it I intentionally gave all three charts the same x-axis scaling to make them easier to compare. I do still like the idea of them being all the same, but I agree that a few extra high and extra low (negative!) team ratings are making it look bad. I was also hoping they might do some adjustments to bring is back more in line with the 1v1 but probably shouldn't hold my breath for that to happen. I'll have a look at scaling each chart separately based on it's data.

**Comment by thbrown** [comment]
Fixed in 93fc2290408175ed1ce09491e96f78300ce27b66 charts now scale according to the smallest and largest x value they contain. I may change this back if the team ratings ever start to look similar to the 1v1 ratings again.

**Comment by dffvb** [comment]
Looks so much nicer now! - thanks a lot :-) On my pointless mission from ELO 500 to 1000 I can now exactly tell, where I am ^^ (currently 800)
